import { Oswald, Figtree, Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const oswald = Oswald({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-oswald",
});

const jakarta = Plus_Jakarta_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-jakarta-sans",
});

const figtree = Figtree({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-figtree",
});

export const lufga = localFont({
  src: [
    {
      path: "../../public/fonts/LufgaBold.woff",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-lufga",
});

// export const metadata = {
//   title: "Portal X",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${oswald.variable} ${figtree.variable} ${jakarta.variable} ${lufga.variable}`}
      >
        <header>
          <Navbar />
        </header>

        <main>{children}</main>
        
        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  );
}
